src/main/java/co/gov/gobierno/Controller/ChangePasswordController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.gov.gobierno.Controller;

import co.gov.gobierno.DTO.AyudaDTO;
import co.gov.gobierno.DTO.PropertieDTO;
import co.gov.gobierno.DTO.ThirdDTO;
import co.gov.gobierno.DTO.WebServiceDTO;
import co.gov.gobierno.Service.CertificateRequestService;
import co.gov.gobierno.Service.ChangePasswordService;
import co.gov.gobierno.Service.TerceroService;
import co.gov.gobierno.Service.WebService;
import co.gov.gobierno.Util.EmailHandler;
import co.gov.gobierno.Util.PropertiesHandler;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import org.slf4j.LoggerFactory;

/**
 *
 * @author DELL
 */
@ManagedBean
@RequestScoped
public class ChangePasswordController implements Serializable
{
    private static long serialVersionUID = 1L;
    private static final org.slf4j.Logger log = LoggerFactory.getLogger(ChangePasswordController.class);
    
    private boolean alertShow = false;
    private boolean alertStyle = false;
    private String alertMessage = "";
    private List<PropertieDTO> listPropertieDTOs;
    
    private ThirdDTO objThirdDTO;
    
    private String email = "";
    private String passConfirm = "";
    private String pass = "";
    
    private List<AyudaDTO> listAyudaDTO;
    private Map<String,String> MapAyudaDB;
    private String UrlVideoRegistro;

    
    @ManagedProperty(value="#{indexController}")
    private IndexController indexController;

    @EJB
    WebService ws;
    @EJB
    ChangePasswordService cps;
    
    @EJB
    TerceroService ts;
    
    public void changePassword()
    {
        try
        {
            if(this.pass.equals(this.passConfirm))
            {
                if(this.objThirdDTO.getEmail().equals(this.email))
                {
                    WebServiceDTO objWebServiceDTO = new WebServiceDTO();
                    String token = ts.ModificarPassword(indexController.getObjThirdDTO().getUser(), this.passConfirm, indexController.getObjThirdDTO().getPass());
                    objWebServiceDTO = cps.ChangePassword(this.objThirdDTO, this.pass, indexController.getAuthenticationToken(), this.listPropertieDTOs);
                    if (token.isEmpty()) {
                    	objWebServiceDTO.setRespuesta(false);
                    }
                    setAlertShow(true);
                    if(objWebServiceDTO.isRespuesta())
                    {
                    	///alonso
                    	 String pass = "";
                        /*String emailResult = EmailHandler.EnviarMensaje(this.email, "Cambio de contraseña exitoso", "Estimado (a) ciudadano (a)" +
                                "<br><br>" +
                                "Se actualiz&oacute; satisfactoriamente el usuario " + this.objThirdDTO.getUser() + " y Contrase&ntilde;a " + this.pass + " en la aplicaci&oacute;n.<br>" +
                                "<br>Para continuar con su solicitud <br><a href='" + PropertiesHandler.PropertieValueOfKeyFromDB(listPropertieDTOs, "urlLogin") + "' target='_blank'>" +
                                "haga clic aqui</a><br><br><br><br><br><p style='font-size:10px'>\"Este correo es de tipo informativo; por favor no responda a este mensaje. Para contactarnos puede hacerlo a trav&eacute;s de la p&aacute;gina de la Secretar&iacute;a Distrital de Gobierno: <a href='http://www.gobiernobogota.gov.co' target='_blank'>http://www.gobiernobogota.gov.co</a>\"</p><br>", this.listPropertieDTOs);*/

                        String emailResult = EmailHandler.EnviarMensaje(this.email, "Cambio de contraseña exitoso", "Estimado (a) ciudadano (a)" +
                                                        "<br><br>" +
                                                        "Se actualiz&oacute; satisfactoriamente el usuario " + this.objThirdDTO.getUser() + " " /*+ this.pass + */ +" .<br>" +
                                                        "<br>Para continuar con su solicitud<br><a href='" + PropertiesHandler.PropertieValueOfKeyFromDB(listPropertieDTOs, "urlLogin") + "' target='_blank'>" +
                                                        "haga clic aqui</a><br><br><br><br><br><p style='font-size:10px'>\"Este correo es de tipo informativo; por favor no responda a este mensaje. Para contactarnos puede hacerlo a trav&eacute;s de la p&aacute;gina de la Secretar&iacute;a Distrital de Gobierno: <a href='http://www.gobiernobogota.gov.co' target='_blank'>http://www.gobiernobogota.gov.co</a>\"</p><br>", this.listPropertieDTOs);
                        if(!emailResult.contains("Error"))
                        {
                            setAlertShow(true);
                            setAlertStyle(true);
                            setAlertMessage("El cambio de contraseña fue exitoso, el usuario y la nueva contraseña fueron "
                                    + "enviados al correo " + this.getEmail());
                        }
                        else
                        {
                            setAlertShow(true);
                            setAlertStyle(false);
                            setAlertMessage("Error al enviar el email.");
                        }
                        
                    }
                    else
                    {
                        setAlertStyle(false);
                        setAlertMessage("Ha ocurrido un error en el sistema por favor comuníquese con el administrador del sistema.");
                    }
                    this.email = "";
                }
                else
                {
                    setAlertShow(true);
                    setAlertStyle(false);
                    setAlertMessage("El correo electrónico no se encuentra registrado");
                }
            }
            else
            {
                setAlertShow(true);
                setAlertStyle(false);
                setAlertMessage("La validacion de la contraseña es incorrecta.");
            }
        }
        catch(Exception e)
        {
            setAlertShow(true);
            setAlertStyle(false);
            setAlertMessage("Ha ocurrido un error al enviar el email. Contacte al administrador del sistema e intentelo más tarde.");
            // setAlertMessage("Ha ocurrido un error inesperado. Contacte al administrador del sistema e intentelo más tarde.");
            log.error("Error: " + e.toString());
        }
    }
    
    @PostConstruct
    public void Init()
    {
        try
        {
            this.objThirdDTO = indexController.getObjThirdDTO();
            this.listPropertieDTOs = indexController.getListPropertieDTOs();
            this.listAyudaDTO = PropertiesHandler.GetAyudaDB();
            this.MapAyudaDB = PropertiesHandler.AyudaDB(listAyudaDTO, "CambioContrasena");
            if(MapAyudaDB.get("vTipo").equals("1"))
            {
                           this.setUrlVideoRegistro("<iframe width='600' height='315'  src='"+MapAyudaDB.get("vUrl")+"' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>");
            }
            if(MapAyudaDB.get("vTipo").equals("2"))
            {
                          this.setUrlVideoRegistro("<img width='600' height='315' src='"+MapAyudaDB.get("vUrl")+"'/>");
            }
        }
        catch(Exception e)
        {
            setAlertShow(true);
            setAlertStyle(false);
            setAlertMessage("Ha ocurrido un error inesperado. Contacte al administrador del sistema e intentelo más tarde.");
            setAlertMessage("Ha ocurrido un error al enviar el email. Contacte al administrador del sistema e intentelo más tarde.");
            log.error("Error: " + e.toString());
        }
    }
    
    public boolean isAlertShow() {
        return alertShow;
    }

    public void setAlertShow(boolean alertShow) {
        this.alertShow = alertShow;
    }

    public boolean isAlertStyle() {
        return alertStyle;
    }

    public void setAlertStyle(boolean alertStyle) {
        this.alertStyle = alertStyle;
    }

    public String getAlertMessage() {
        return alertMessage;
    }

    public void setAlertMessage(String alertMessage) {
        this.alertMessage = alertMessage;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassConfirm() {
        return passConfirm;
    }

    public void setPassConfirm(String passConfirm) {
        this.passConfirm = passConfirm;
    }

    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public ThirdDTO getObjThirdDTO() {
        return objThirdDTO;
    }

    public void setObjThirdDTO(ThirdDTO objThirdDTO) {
        this.objThirdDTO = objThirdDTO;
    }

    public void setIndexController(IndexController indexController) {
        this.indexController = indexController;
    }

    public List<PropertieDTO> getListPropertieDTOs()
    {
        return listPropertieDTOs;
    }

    public void setListPropertieDTOs(List<PropertieDTO> listPropertieDTOs)
    {
        this.listPropertieDTOs = listPropertieDTOs;
    }
    
    
     public String getUrlVideoRegistro()
    {
        return UrlVideoRegistro;
    }

    public void setUrlVideoRegistro(String UrlVideoRegistro)
    {
        this.UrlVideoRegistro = UrlVideoRegistro;
    }

    public List<AyudaDTO> getListAyudaDTO()
    {
        return listAyudaDTO;
    }

    public void setListAyudaDTO(List<AyudaDTO> listAyudaDTO)
    {
        this.listAyudaDTO = listAyudaDTO;

src/main/java/co/gov/gobierno/Controller/ForgotPasswordController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.gov.gobierno.Controller;

import co.gov.gobierno.DTO.AyudaDTO;
import co.gov.gobierno.DTO.PropertieDTO;
import co.gov.gobierno.DTO.ThirdDTO;
import co.gov.gobierno.DTO.WebServiceDTO;
import co.gov.gobierno.Service.ChangePasswordService;
import co.gov.gobierno.Service.IndexService;
import co.gov.gobierno.Service.LoginService;
import co.gov.gobierno.Service.RememberPasswordService;
import co.gov.gobierno.Service.WebService;
import co.gov.gobierno.Util.EmailHandler;
import co.gov.gobierno.Util.EncryptHandler;
import co.gov.gobierno.Util.PropertiesHandler;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.slf4j.LoggerFactory;

/**
 *
 * @author DELL
 */
@ManagedBean
@ViewScoped
public class ForgotPasswordController implements Serializable
{
    
	private static final org.slf4j.Logger log = LoggerFactory.getLogger(ForgotPasswordController.class);
    private boolean alertShow;
    private boolean alertStyle;
    private String alertMessage;
    private List<PropertieDTO> listPropertieDTOs;
    private List<AyudaDTO> listAyudaDTO;
    private Map<String,String> MapAyudaDB;
    private String UrlVideoRegistro;
    
    private String user;
    private String email;
    private String url;
    
    @ManagedProperty(value="#{indexController}")
    private IndexController indexController;
    
    public String ForgotPassword()
    {
        indexController.setObjThirdDTO(new ThirdDTO());
        indexController.getObjThirdDTO().setUser(this.getUser());
        indexController.setListPropertieDTOs(this.getListPropertieDTOs());
        indexController.ConsultThird();
        this.setUrl(PropertiesHandler.PropertieValueOfKeyFromDB(listPropertieDTOs, "urlLogin"));
        if (indexController.getObjThirdDTO() != null)
        {
            this.setEmail(indexController.getObjThirdDTO().getEmail());
            if(getEmail()!=null && !email.equals(""))
            {
                String key = "Bar12345Bar12345"; // 128 bit key
                String initVector = "RandomInitVector"; // 16 bytes IV

                String enc64 = EncryptHandler.encrypt(key, initVector, user);
                log.info(enc64);
                //String link = "h" + "ttp://localhost:7001/TRAMITES/faces/rememberpassword.xhtml?user=" + enc64;
                String link = url+"faces/rememberpassword.xhtml?user=" + enc64;
                String emailResponse = EmailHandler.EnviarMensaje(this.getEmail(), "Recuperación contraseña", "<html><meta charset=\"UTF-8\"/><div style='text-align:left;'>Estimado (a) ciudadano (a)<br>"
                        + "Para Cambiar su contrase&ntilde;a, siga el siguiente Enlace: <br> <a href=" + link+" target='_blank'>Haga clic aqui para cambiar su contrase&ntilde;a</a><br><br><br>"
                                + "<br><br><br><br><p style='font-size:10px'>\"Este correo es de tipo informativo; por favor no responda a este mensaje. Para contactarnos puede hacerlo a trav&eacute;s de la p&aacute;gina de la Secretar&iacute;a Distrital de Gobierno: <a href='http://www.gobiernobogota.gov.co' target='_blank'>http://www.gobiernobogota.gov.co</a>\"</p><br></div></html>", this.getListPropertieDTOs());
                if(!emailResponse.contains("Error"))
                {
                    this.alertShow = true;
                    this.setAlertStyle(true);
                    this.setAlertMessage("Se ha enviado un correo electrónico a: " + this.getEmail() + " con la recuperación de la contraseña.");
                }
                else
                {
                    this.alertShow = true;
                    this.setAlertStyle(false);
                    this.setAlertMessage("Error enviando el email");
                }
            }
            this.setEmail("");
            return null;
        } else {
            this.alertShow = true;
            this.setAlertStyle(false);
            this.setAlertMessage("El Usuario Ingresado no Existe");
            this.setEmail("");
            return null;
        }
    }
    
    public String Back()
    {
        return"back";
    }
    
    @PostConstruct
    public void Init()
    {
        try
        {
            this.listPropertieDTOs = PropertiesHandler.GetPropertiesListFromDB();
            this.listAyudaDTO = PropertiesHandler.GetAyudaDB();
            this.MapAyudaDB = PropertiesHandler.AyudaDB(listAyudaDTO, "RecuperarContrasena");
            if(MapAyudaDB.get("vTipo").equals("1"))
            {
                           this.setUrlVideoRegistro("<iframe width='600' height='315'  src='"+MapAyudaDB.get("vUrl")+"' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>");
            }
            if(MapAyudaDB.get("vTipo").equals("2"))
            {
                          this.setUrlVideoRegistro("<img width='600' height='315' src='"+MapAyudaDB.get("vUrl")+"'/>");
            }
        }
        catch(Exception e)
        {
            setAlertShow(true);
            setAlertStyle(false);
            setAlertMessage("Ha ocurrido un error inesperado, contacte al administrador del sistema.");
        }
    }

    public boolean isAlertShow()
    {
        return alertShow;
    }

    public void setAlertShow(boolean alertShow)
    {
        this.alertShow = alertShow;
    }

    public boolean isAlertStyle()
    {
        return alertStyle;
    }

    public void setAlertStyle(boolean alertStyle)
    {
        this.alertStyle = alertStyle;
    }

    public String getAlertMessage()
    {
        return alertMessage;
    }

    public void setAlertMessage(String alertMessage)
    {
        this.alertMessage = alertMessage;
    }

    public List<PropertieDTO> getListPropertieDTOs()
    {
        return listPropertieDTOs;
    }

    public void setListPropertieDTOs(List<PropertieDTO> listPropertieDTOs)
    {
        this.listPropertieDTOs = listPropertieDTOs;
    }

    public String getUser()
    {
        return user;
    }

    public void setUser(String user)
    {
        this.user = user;
    }

    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public void setIndexController(IndexController indexController)
    {
        this.indexController = indexController;
    }

    public String getUrl()
    {
        return url;
    }

    public void setUrl(String url)
    {
        this.url = url;
    }
    
     public String getUrlVideoRegistro()
    {
        return UrlVideoRegistro;
    }

    public void setUrlVideoRegistro(String UrlVideoRegistro)
    {
        this.UrlVideoRegistro = UrlVideoRegistro;
    }

    public List<AyudaDTO> getListAyudaDTO()
    {
        return listAyudaDTO;
    }

    public void setListAyudaDTO(List<AyudaDTO> listAyudaDTO)
    {
        this.listAyudaDTO = listAyudaDTO;
    }

    public Map<String, String> getMapAyudaDB()
    {
        return MapAyudaDB;
    }

    public void setMapAyudaDB(Map<String, String> MapAyudaDB)
    {
        this.MapAyudaDB = MapAyudaDB;
    }

}

src/main/webapp/expiredSession.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html lang="es"  xmlns = "http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" >



    <ui:composition template="/template.xhtml">
        <ui:define name="content">
            <div class="container">
               
                <h:form id="loginform2">
                    
                    <br/>
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3" style="text-align: center">
                            <h4>Su Sesión ha expirado. <br/> Vuelva a Iniciar Sesión para continuar.</h4>
                            
                            
                            
                            <h:commandLink action="login" value="Iniciar Sesion" immediate="true"
                                           onclick="block()" class="btn btn-primary"/>
                        </div>
                        
                    </div>
                    <br/>
                </h:form>
            </div>
            <script>
            		$('.numerico').on('keypress', function (e)
	                {
	                    return (e.charCode &gt;&#61; 48 &amp;&amp; e.charCode &lt;&#61; 57) || (e.key &#61;&#61; "Backspace");
	                });
            
                //Bloquea la pantalla.
                function block()
                {
                    $.blockUI({message: '<h3><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>  Cargando...</h3>', css: {
                            border: 'none',
                            padding: '15px',
                            backgroundColor: '#000',
                            '-webkit-border-radius': '10px',
                            '-moz-border-radius': '10px',
                            opacity: .5,
                            color: '#fff'
                        }});
                }
                ;
                //------------------------
                $(document).ready(function ()
                {
                    $(userMessage).html('');
                    //Desbloquea la pantalla.
                    $.unblockUI();
                });
            </script>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html lang="es"  xmlns = "http://www.w3.org/1999/xhtml"  xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">



    
    


    <ui:composition template="/sidebartemplate.xhtml">
        <ui:define name="content">
            <h:form id="home">
                <div class="col-md-10">
                    <section>
                        <div class="well">
                            <div class="row">
                                <div class="col-md-12" style="text-align:center">
                                    <h3><strong>Inicio</strong></h3>
                                </div>
                            </div>
                        </div>
                        <div class="well well-sm">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div class="row ">
                                        <div class="col-md-4 col-md-offset-1 navbar navbar-default sidebar hidden-sm hidden-xs " style="padding: 2%; text-align: center">
                                            <label><strong>Certificados Residencia</strong></label>                                            
                                                <img src="#{loginController.urlImgCR}" alt="" style="width: 100%"/>
                                        </div>
                                        <div class="col-md-4 col-md-offset-1 navbar navbar-default sidebar hidden-sm hidden-xs " style="padding: 2%; text-align: center">
                                            <label><strong>Propiedad Horizontal</strong></label>
                                            <img src="#{loginController.urlImgPH}" alt="" style="width: 100%"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/rememberpassword.xhtml
<!DOCTYPE html>
<html lang="es"  xmlns = "http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      >



    <ui:composition template="/template.xhtml">
        <ui:define name="content">
            <h:form id="loginform">
                <h:panelGroup layout="block" id="registeralert">
                    <h:panelGroup layout="block" rendered="#{rememberPasswordController.alertShow}">
                        <div class="#{rememberPasswordController.alertStyle ? 'alert alert-success alert-dismissible' : 'alert alert-warning alert-dismissible'}"
                             id="alert" align="center">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&#215;</a>
                            <h:outputLabel id="finalMessage" value="#{rememberPasswordController.alertMessage}"/>
                        </div>
                    </h:panelGroup>
                </h:panelGroup>

                <div class="well">
                    <div class="row">
                        <div class="col-md-12" style="text-align:center">
                            <h3><strong>Cambio de contraseña</strong></h3>
                        </div>
                    </div>
                </div>
                <div class="well well-sm">
                    <div class="panel-heading">
                        <img src="images/Help.png" style="width: 25px"/>
                        <label><strong>Los campos marcados con <label style="color:red"></label><label style="color:red">*</label> son obligatorios.</strong></label>
                        <span  id="Help" onMouseOver="mano(this)" onclick="fpopover(); return false;"   style="width: 4%; text-transform:bold; cursor:hand" data-placement="left" class="pull-right" data-toggle="popover"   data-html="true" data-content="#{rememberPasswordController.urlVideoRegistro}" >Ayuda</span>
                        <img src="images/Ayuda.png" style="width: 25px" class="pull-right"/>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3 " style="text-align: center ">
                                    <label>Contraseña Nueva</label><label style="color:red">*</label>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-lock"></i>
                                        </span>
                                        <h:inputSecret id="txtPassword" required="true" class="form-control" maxlength="15" 
                                                       value="#{rememberPasswordController.pass}" requiredMessage="Este campo es requerido."/>
                                    </div>
                                    <h:message for="txtPassword" style="color:#ff0000" />
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3 " style="text-align: center ">
                                    <label>Confirmar Contraseña</label><label style="color:red">*</label>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-lock"></i>
                                        </span>
                                        <h:inputSecret id="txtPasswordNuevoConfirmar" required="true" class="form-control" 
                                                       maxlength="15" value="#{rememberPasswordController.passConfirm}"
                                                       requiredMessage="Este campo es requerido."/>
                                    </div>
                                    <h:message for="txtPasswordNuevoConfirmar" style="color:#ff0000" />
                                    <span id='message'></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="well">
                    <div class="row ">
                        <div class="col-md-6 col-md-offset-3 " style="text-align: center ">
                            <h:commandButton value="Actualizar" styleClass="btn btn-default btn-block"
                                             type="submit" action="#{rememberPasswordController.ChangePassword()}" onclick="block()"/>
                        </div>
                    </div>
                </div>

            </h:form>
            <script>
            		$('.numerico').on('keypress', function (e)
	                {
	                    return (e.charCode &gt;&#61; 48 &amp;&amp; e.charCode &lt;&#61; 57) || (e.key &#61;&#61; "Backspace");
	                });
            
                //Bloquea la página.
                function block()
                {
                    $.blockUI({message: '<h3><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>  Cargando...</h3>', css: {
                            border: 'none',
                            padding: '15px',
                            backgroundColor: '#000',
                            '-webkit-border-radius': '10px',
                            '-moz-border-radius': '10px',
                            opacity: .5,
                            color: '#fff'
                        }});
                }
                ;
                //-----------------------------------
                $(document).ready(function ()
                {
                    $('[data-toggle="popover"]').popover();
                    //Desbloquea la pagina
                    $.unblockUI();
                });
                
                      function fpopover()
                {
                    var p = $('[data-toggle="popover"]').popover({
                        title: '<span class="text-info"><strong> Ayuda</strong></span>' +
                                '<button type="button" id="close" class="close" onclick="$(&quot;#Help&quot;).popover(&quot;hide&quot;);">X</button>'
                    });
                    p.on("show.bs.popover", function (e) {
                        p.data("bs.popover").tip().css({"max-width": "100%"});
                    });
                }
                
                 function mano(a) {
                    if (navigator.appName === "Netscape") {
                        a.style.cursor = 'pointer';
                    } else {
                        a.style.cursor = 'hand';
                    }
                }
            </script>
        </ui:define>
    </ui:composition>
</html>